name: Bug Report
description: Open a report for an issue or bug
title: "Title for this issue"
labels: ["bug", "investigating"]
assignees:
  - "ProbablyRaging"
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue?
      description: A clear and concise description of your issue or bug
      paceholder: Include any steps that might help reproduced the issue, screenshots of the issue, Chrome dev tools logs
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Vivaldi
        - Microsoft Edge
        - Other
  - type: checkboxes
    id: version
    attributes:
      label: Latest browser version?
      options:
        - label: Yes
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
